### ISSUE TITLE
밴을 당한 이후 쿠키가 지워지지 않아 로그아웃이 안된채로 남아있는 문제가 있습니다

### ISSUE THREAD

**Issue by GulSauce** [Stageus/kkujjang-react#96]
![image](https://github.com/Stageus/kkujjang-react/assets/139232765/d45525d6-1a78-4b00-b1bb-323d2458aa7b)

**Comment by jadugamja** [comment]
플로우 확인 요청합니더~~ 다음과 같은 상황에서 발생한 에러 맞나요?
1. 회원 A 로그인 ---------------------------------------------> 3. 강제 로그아웃 처리
                            -> 2. 관리자가 회원 A 계정 비활성화(밴)

**Comment by GulSauce** [comment]
앗 플로우 말씀드리겠습니다
1. 로그인 후 사용자의 홈화면
![image](https://github.com/Stageus/kkujjang-react/assets/139232765/77d9891a-f02f-441b-96cc-abb5b1aceef2)

2. 운영자가 밴을 함
3. 95번 이슈 발생
![image](https://github.com/Stageus/kkujjang-react/assets/139232765/e69474a4-54ef-479e-a6b5-905e92edc93e)

4. 주소창에 kkujjang-dev.loasim.com를 입력하여 이동
![image](https://github.com/Stageus/kkujjang-react/assets/139232765/d3e803bf-3806-4c45-ab52-af69ac8dd5b0)
